[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "src/lib.rs"

[[bin]]
name = "zero2prod"
path = "src/main.rs"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }

[dev-dependencies]
reqwest = "0.12.24"
